### ISSUE TITLE
Day03 (à voir) - Airflow

### ISSUE THREAD

**Issue by ErenO** [42-AI/bootcamp_data-engineering#10]
## Global notes:
L'objectif du jour est la prise en main de l'outil Airflow, cette journée a pour but de comprendre le potentiel de l'outil, d'utiliser le maximum de features.
Les exercices ont pour objectif de charger un table de fait sur plusieurs jours et d'utiliser les différents services d'AWS (s3, redshift, dynamodb)
Liste des exercices pour la journée sur Airflow:
L'ordre des exercices est à voir 
### ex00:
- [x] 1. Lancer le docker en local
- [x] 2. Créer un dag load_fact_* (nom à voir)

### ex01:
- [ ] 1.  Faire un pythonoperator qui charge les fichiers dans un dossier temporaire `/tmp/data` (dans le docker) sur s3
- [ ] 2.  

### ex02:
- [ ] 1. Faire des redshiftoperator pour creer les tables de staging
- [ ] 2. 

### ex03:
- [ ] 1. Faire un pythonoperator (fonction python) pour transaformer la donnee (aggregation, group by, etc)
- [ ] 2. 

### ex04:
- [ ] 1. Charger les tables de staging  
- [ ] 2. 

### ex05:
- [ ] 1. charger la table de fait
- [ ] 2. 

### ex06:
- [ ] 1. CheckpointDynamoDb 
- [ ] 2.

**Comment by fxbabin** [comment]
No longer part of the project for the moment
