### ISSUE TITLE
Misunderstanding over Games filter

### ISSUE THREAD

**Issue by Medno** [42-AI/bootcamp_data-engineering#32]
* Day: 00
* Exercise: 02

Hi there,
I've noticed something weird about the Games filter and the number of lines we have to find at the end in the appstore_games_genres.

With a classic **Games,** filter or something similar we get close to the found number of lines (~44352 lines). But after looking at value_counts in df_genres, we find remaining Games genres.

It might be because of the filter match only with genres that begins with **Games** but remaining genres like those are not took into account:

> Strategy, Games

or

> Strategy, Games, Adventure

I would suggest replacing the match regexp with following filter : 
```python
> df_genres['Genres'].replace('Games, |Games|, Games', '', regex=True, inplace=True)
```

Or after exploding the data :
```python
> df_genres = df_genres[df_genres['Genres'] != 'Games']
```

Hope it helps !
Thanks again for this bootcamp 💪

**Comment by fxbabin** [comment]
Fixed normally :)
